root:
    _node: { service: site, method: getOne, template: main_page.tpl }
    about: { _node: { service: site, variable: article, action: getArticle, template: about.tpl } }
    api: 
        _node: { router: rest_api_router }
    news: 
        _node: { service: news, action: getList, template: list.tpl }
        _default: 
            _node: { variable: pk_news, greedy: true, service: news, action: getList, template: list.tpl }
    catalog: 
        _node: { service: catalog, action: getList, template: tree.tpl }
        _default: 
            _node: { variable: catalog_path, greedy: true, service: catalog, action: getNode, module: news, template: list.tpl }

