root:
    _node: { service: news, method: getList, module: news, template: list.tpl }
    test2: { _node: { service: news, action: getList, module: news, template: list.tpl } }
    api: 
        _node: { router: another_router }
        _default: { _node: { variable: test_var2, service: news, action: getList, module: news, template: list.tpl } }
    _default: 
        _node: { variable: test_var1, service: news, action: getList, module: news, template: list.tpl }
        news: { _node: { router: web_service/router } }
        _default: 
            _node: { variable: test_var2, greedy: true, service: news, action: getList, module: news, template: list.tpl }

