#common settings
db: </mysql/main

#modules
mysql:
    connections:
        main:
            link: mysql:dbname=reactor;host=127.0.0.1;port=3306
            user: root
            password: test
            options: "<?[ \\PDO::ATTR_PERSISTENT => true ]"

web:
    site_tree: <? $app->yml_loader->lazyLoad('config/site_tree.yml')
    tpl_bin: <? BASE_DIR . 'var/tpl_bin/'

