modules:
    controllers:
        class: \Reactor\WebService\SlimControllerGenerator\Module
        config:
            dynamic:
                bin_generated_path: '@folders/bin_generated'
                controllers:
                    test_controller:
                        _settings:
                            defaults:
                                service: myService
                        test1: { service: blah, method: mblah1, arguments: [ "$$request->get->getInteger('var1', 1)" ] }
                        test2: { service: blah, method: mblah2, arguments: [ "$$request->get->getInteger('var2', 1)" ] }
                        test3: { service: blah, method: mblah3, arguments: [ "$$request->get->getInteger('var3', 1)" ] }
                        test4: { service: blah, method: mblah4, arguments: [ "$$request->get->getInteger('var4', 1)" ] }

