handler: [ /site/controller, index ]
nodes: 
    news:
        handler: [ /news/collection, getPage ]
        # handler: [ /news/printer, handle ]
        template: [ /news, news.tpl ]
        template_wrap: [ /news, main.tpl ]
        # final: true
        map:
            - [get, page, 1, integer]
            - [static, 10]
        nodes:
            $any:
                variable: here
                handler: [ /news/printerw, handler ]
                template: [ /news, news.tpl ]
    catalog:
        handler: [ /catalog/list, list ]
        final: true
    node:
        handler: [ /site/controller, code404 ]
        template: [ /module, template.tpl ]
        template_wrap: [ /module, template.tpl ]
        final: true
        map: [ config ]
        mapper: [ /mapper/service, method ]
error:
    template: [ /web, error.tpl ]
    handler: error_handler
