handler: [ /site/controller, index ]
nodes: 
    news:
        handler: [ /news/collection, getPage ]
        # handler: [ /news/printer, handle ]
        template: [ /news, news.tpl ]
        template_wrap: [ /news, main.tpl ]
        # final: true
        map:
            - [get, page, 1, integer]
            - [static, 10]
        nodes:
            $any:
                variable: here
                handler: [ /news/printerw, handler ]
                template: [ /news, news.tpl ]

error:
    template: [ /web, error.tpl ]
    handler: error_handler
