handler: [ /site/controller, index ]
nodes: 
    news:
        handler: [ /news/collection, getPage ]
        # handler: [ /news/printer, handle ]
        template: [ /news, news.tpl ]
        template_wrap: [ /news, main.tpl ]
        # final: true
        map:
            - [get, page, 1, isNatural]
            - [static, 10]
        nodes:
            $any:
                variable: page
                handler: [ /news/collection, getPage ]
                template: [ /news, news.tpl ]
                template_wrap: [ /news, main.tpl ]
                map:
                    - [variable, page, 1, isNatural]
                    - [static, 10]
            add:
                handler: [ /news/form, handle ]
                template: [ /news, form.tpl ]
                template_wrap: [ /news, main.tpl ]

error:
    template: [ /web, error.tpl ]
    handler: error_handler
